### ISSUE TITLE
Support OpsGenie

### ISSUE THREAD

**Issue by ayanich** [echoboomer/incident-bot#319]
OpsGenie is Atlassian's alert management tool, similar to PagerDuty.

**Comment by tasuve-tuum** [comment]
+1 Also would like to get this feature

**Comment by echoboomer** [comment]
@ayanich @tasuve-tuum Just released `v1.5.0` with support for Opsgenie. Keep in mind that I developed this with a basic tier for Opsgenie since I don't have an enterprise account. If you're able to give this a spin and let me know what issues you run into, that would be much appreciated. Please feel free to open new issues as you go along.

In general, this replicates the same features we have with PagerDuty minus the UI changes which are currently unsupported and will be fixed in a follow up release. You should be able to enable Opsgenie and use the `@incident-bot pager` command to list who is on call as well as creating alerts, not incidents, to page people.
