### ISSUE TITLE
[FEATURE] Possibility to have a Jira ticket and Confluence RCA page on the channel description

### ISSUE THREAD

**Issue by luismartins-td** [echoboomer/incident-bot#421]
**Is your feature request related to a problem? Please describe.**
Possibility to have a Jira ticket and Confluence RCA page on the channel description. We already have the zoom.

**Comment by ImDevinC** [comment]
A few questions this raises:
- What if there's multiple Jira tickets?
- The RCA is not created until the incident is resolved, so what should the link point to?

**Comment by luismartins-td** [comment]
What if there are multiple Jira tickets?
I think that for each incident you should have only one ticket. If it makes sense to have multiple you can have an epic with multiple tickets

The RCA is not created until the incident is resolved, so what should the link point to?
I understand this one because when you resolve the incident the RCA is created with all the information related. But it's possible to add it only when it's resolved? So this way you can have all the info in one Slack channel? Because in my case I will not use the RCA slack channel. We could have an option to create it or not.

**Comment by ImDevinC** [comment]
> I think that for each incident you should have only one ticket. If it makes sense to have multiple you can have an epic with multiple tickets

I don't know if everyone uses tickets the same way, so I think having some idea of how to handle multiple tickets would be preferred

> I understand this one because when you resolve the incident the RCA is created with all the information related. But it's possible to add it only when it's resolved? So this way you can have all the info in one Slack channel? Because in my case I will not use the RCA slack channel. We could have an option to create it or not.

I agree with this. We don't tend to use the separate RCA channel either, so having an option for this would be nice in my opinion.

What if, for both of these options, instead of adding to the channel topic we updated the main pinned message and/or pinned new messages?

**Comment by echoboomer** [comment]
I'm probably going to remove the RCA channel all together because it was another request made while I was developing the bot that doesn't seem useful anymore. In doing so, I'll just send the RCA message to the incident channel and we shouldn't need to put it in the topic since it will be mentioned in the channel's resolution messages.

**Comment by echoboomer** [comment]
Latest release `v1.8.4` reasonably handles this by removing the RCA channel and adding the message about the RCA to the incident channel with a pin. The title has also been simplified. We may support further customization of the title in the future.
